### ISSUE TITLE
REMOVE LOGIN

### ISSUE THREAD

**Issue by SiyamF** [patrickjquinn/P-Brain.ai#103]
I wanna remove the login system from brain, Like whenever i visit the localhost:4567 it will start working and wil not ask for username and password

**Comment by patrickjquinn** [comment]
This is very much a project you extend yourself I’m afraid. You can go into the node server and remove all basic auth from there.

**Comment by SiyamF** [comment]
Hi pat, 
Thanks for replying,  i am a big fan of yours, this project is amazing......
I am new on node and express so i am not understanding what to remove and how, can you please explain little more.....
Need it badly please help me

**Comment by SiyamF** [comment]
waiting for your answer :)
