### ISSUE TITLE
Need Help To Change Database Sqlite3 to Mysql

### ISSUE THREAD

**Issue by alexia-rose** [patrickjquinn/P-Brain.ai#107]
I am new on web apps and coding currently learning Mysql and nodejs, I really like this AI, but it seems working with sqlite3 but I wanna change it to MySQL and remove that sqlite3 (it was too much annoying to install also) can anyone give me ideas how can I do it, as a beginner the code seems too much professional to me?

**Comment by timstableford** [comment]
Could you elaborate on how SQLite was hard to install please? It should just work running an `npm install` command with no external dependencies.

To use MySQL create a config.json in the projects root that looks something like this:
```json
{
  "databaseType": "mysql",
  "databaseArguments": {
    "host": "127.0.0.1",
    "username": "root",
    "password": "example",
    "database": "pbrain"
  }
}
```
https://github.com/patrickjquinn/P-Brain.ai/blob/master/db/index.js

**Comment by alexia-rose** [comment]
**thanks for response** 
I save config.json on the root folder and created a DB on MySQL but still, it's running over sqlite3
![Capture1](https://user-images.githubusercontent.com/88448176/128295982-30358290-3d67-48da-bdcb-a1e21aefa49e.PNG)
![Capture](https://user-images.githubusercontent.com/88448176/128296061-274a8f76-093e-4d34-9c99-96de63a4db2a.PNG)

and I encountered a random error on installing SQLite after that I find a solution from StackOverflow, that I had to uninstall SQLite then have to clear cache, and installed it again....

**Comment by SiyamF** [comment]
Save the config.json file on "db" folder

**Comment by alexia-rose** [comment]
Thanks, @SiyamF  its solve the problem
