### ISSUE TITLE
Frontend aborts

### ISSUE THREAD

**Issue by darkstardxm** [patrickjquinn/P-Brain.ai#13]
I am running P-Brain.ai in Docker

When verbally asking Brain for the time Chrome shows
resp_types.js:91 aborted

When using HTTP it responds normally
{"msg":"It is currently 5° and Clear","type":"weather","question":"{what is the weather}"}

I apologize I am not able to provide clearer logs, but given some instruction I would happily provide them. Thanks for your awesome project!

**Comment by patrickjquinn** [comment]
Odd, when running this outside of Docker do you get the same error? The speech recognition portion of the web client is failing (Thats the line thats being specified in the error you've stated)

**Comment by darkstardxm** [comment]
I can't run it outside of Docker on this machine unfortunately (QNAP NAS). Id have to dig out another device to try it on.

**Comment by patrickjquinn** [comment]
Thats even stranger...are you accessing the server locally on the device its running on or are you accessing it from another device on the network?

**Comment by darkstardxm** [comment]
Ahh, it is on another device on the network, and further is not running on the host network and only having the port forwarded. I will try it and return, thank you!

**Comment by patrickjquinn** [comment]
Yep, once you mentioned that it was understanding what you where saying but not getting a response it clicked that it was outside of the network in some way (as the server is writing the IP of its host to a variable file which is then accessed clientside for getting responses)

I'll close this for the moment but if you've any further issues related to this it can be reopened!
