### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rhettl** [patrickjquinn/P-Brain.ai#17]
This library is so cleanly written! I didn't once consider picking up my ax. 

You took a largely confusing subject and very cleanly described it in code so even I (one with no NLP experience) can read and understand it. 

I'm confused on one point though, in `api/ask-core.js`
````javascript
if (confidence > 0.25) {
    throw new Error('error')
}
````

I know that the `confidence` value there is a value from 0-1 describing how sure the algorithm is in classifying the query as the returned label, but why does confidence need to be less than a quarter? In my lay-mind it looks like a statement, "If you are more than a quarter certain of this result, error out." 

Thanks for any clarification you can give!

**Comment by patrickjquinn** [comment]
This is an item which threw me massively too, I think we should put this question to the author of the natural module! It seems the lower the value the higher the confidence, it's very counter intuitive and confusing.

You can test this by swapping out the less than for a greater than. It breaks the whole thing! I'll cover this exact point in my next video to clarify it for future developers :)
