### ISSUE TITLE
Add SSL And Authentication

### ISSUE THREAD

**Issue by timstableford** [patrickjquinn/P-Brain.ai#25]
Some users may want to have this application externally accessible. The app could probably use SSL support and authentication, although that may be tricky over socket.io.

**Comment by patrickjquinn** [comment]
Hey Tim, i've been looking at this, the version that runs on the sample sit patrickjquinn.github.io/P-Brain.ai/ (down the bottom) is hosted on Azure, i've set up all of the needed certs and keys but without a signing authority Its not all that useful :(

Socket.io doesnt seem to work very well in that configuration either, but i'm sure that can be worked around. 

I was hoping to get this working myself so I can have a remote endpoint for the mobile clients. (We would then need to totally abstract the server from all clients and introduce the concept of device based sessions or device profiles)

**Comment by timstableford** [comment]
I'm sure we can implement some sort of token based authentication. Perhaps, use SSL and HTTP basic authentication to get a session token from a URL and then send that session token along with each socket.io packet?

**Comment by patrickjquinn** [comment]
I think a generic token would work best, for browsers you would store the token in local cache and for clients, store it for the life of the session. I'm going to quickly do some research into simple token auth of node 👍 

Also thank you for getting the Android app live in play store! Fantastic stuff, I was going to do the same myself! If you want to remove the '(Unofficial)' suffix at any stage, you have my blessing 👍

**Comment by timstableford** [comment]
Thanks! :+1: Sent an updated name which should show in a couple of hours.

If you're planning to have a shared server then at some point we're going to have to abstract all of the locally stored objects, names, responses etc to be able to go in a database or connect to cloud storage.

**Comment by patrickjquinn** [comment]
Yep, instead of setting up a mongo db based solution (which would mean just one more dependency for anyone looking to set up the project locally), we could just opt for a flat FS based db like https://www.npmjs.com/package/diskdb

So every new user would get their own object in the db and then entries for {queries:<queries.json>, responses:<responses.json>, details: <details.json>, classifier: <classifier.json>}. This would also allow us to create a merged classifier which is trained across all user interaction which we could then propagate to each individual user. 

As for hosting...i've got that covered, instance size and storage requirements shouldn't be an issue in the least.

**Comment by timstableford** [comment]
I feel like flat files could get very messy unless it's done really smartly. I know for instance at the moment every time there's a new response the whole file is overwritten. If you really want to go with flat file on server side we need to ensure that whatever library we use only appends.

It also has the downside that it could only be accessed by one instance at a time. If the server becomes overloaded and we need to spin-up another, then it wouldn't be able to access the DB of the first without further abstraction.

I propose that we essentially keep it as it is currently, but abstract it away a bit more. And then allow a selection of different storage options, the default of which would be flat files. Then server side we could use a database system that can be accessed from multiple instances,

**Comment by patrickjquinn** [comment]
Okay yes you're right, its better done in a totally abstract fashion. This calls for a little bit of investigation on the best way to do so

**Comment by timstableford** [comment]
By the way, https://letsencrypt.org/ offers free SSL certificates supported by most browsers.

**Comment by patrickjquinn** [comment]
Well... I wish i'd known about this sooner, thank!

**Comment by timstableford** [comment]
To be fair, any old domain would do for hosting the demo. It would only be visible to people setting up the mobile apps.

**Comment by patrickjquinn** [comment]
Well this is true, but i'll need to buy a domain with SSL support, so why not get the actual p-brain.ai domain and host the website on it too!

**Comment by patrickjquinn** [comment]
I've added SSL to the project locally but will have to do some slight modifications to make socket.io work with it (i.e secure:true when creating a socket connection)

**Comment by timstableford** [comment]
If it's not done yet, why did you close the issue? Issue tracking is a good thing ;)

**Comment by patrickjquinn** [comment]
I'm not a fan of leaving issue tickets open my man, this is a feature request and not an open issue so I dont want people getting confused and thinking that SSL isnt working when its not there :)

I've re-opened this anyway!

**Comment by timstableford** [comment]
That's a fair point. Thanks for re-opening anyway. I might be imagining features of GitHub, but isn't it possible to tag issues as feature requests, or bugs etc?

**Comment by patrickjquinn** [comment]
Ah going to change that now! Thank you!

**Comment by patrickjquinn** [comment]
Hey @timstableford ignoring SSL & HTTPS for a moment, do you want me to spin up a VM with P-Brain running on it so you can add a remote end point as an option to your Android client?

**Comment by timstableford** [comment]
That sounds like a good plan, have you got a permanent hostname for it?

**Comment by timstableford** [comment]
@patrickjquinn About that branch. Thanks for giving me write access. I'm going to hold off for now though until you've laid down a foundation for the database otherwise I'll just be getting in your way :+1:

**Comment by patrickjquinn** [comment]
Excellent, I'm going to add the appropriate methods, modify read write operations to make use of it and then push :)

**Comment by timstableford** [comment]
I've finished the changes to the Android app ready to be pushed to Play store when we merge to master. I feel like we should finish this integration though first :+1:

**Comment by patrickjquinn** [comment]
You mean finish the work on SSL?

**Comment by timstableford** [comment]
Sorry, that wasn't very clear. Theoretically it should already be SSL capable. I mean I've added authentication support as we've got in the branch.

**Comment by patrickjquinn** [comment]
Ahh yes yes, okay. I'm going to solidify in this branch everything and then merge with master (Probably tomorrow at this stage).

We should probably set out a project feature pipeline and work towards milestones etc so so we know what to tackle next and so on :) maybe in the wiki section?

**Comment by timstableford** [comment]
Sounds good to me.

**Comment by timstableford** [comment]
@patrickjquinn Don't merge it, I just found a bug. Some modules communicate with each other using HTTP requests and that is completely broken with auth.

**Comment by patrickjquinn** [comment]
No problem, which modules?

**Comment by timstableford** [comment]
Timer is the broken one I'm aware of, there may be others though. It's because it's trying to use /api/ask.

**Comment by timstableford** [comment]
I've resolved that bug by making the .query(q) command global. I think we should wait until the two user systems are properly integrated before merging though. I should have time either this evening or next to do that.

Also, a proposition for the database API, which would be accessible through global.db.
# These would be user and skill specific configs, such as the users name, or what the user is calling Brain.
- db.setValue(skill, user, key, value)
- db.getValue(skill, user, key)

# These would be used for config values such as API keys for a skill.
- db.setSkillValue(skill, key, value)
- db.getSkillValue(skill, key)

# These ones would be used for global settings, such as port numbers.
- db.setGlobalValue(key, value)
- db.getGlobalValue(key)

# These would be used for authentication.
- db.addToken(user, token)
- db.deleteToken(token)
- db.getUserFromToken(token)
- db.getUser(username, password) (takes the raw password, used for logins mostly)

There are other methods we'll need to add for adding and deleting users, but that is a future problem :+1:

**Comment by patrickjquinn** [comment]
I've added the bulk of the methods as stubs, also added in some boilerplate logic while I get the auth working with the db.

I'm still struggling to wrap my head around how a skill developer would add the config stuff for that skill to the db in an automated fashion and I still think a local json config would be a much more modular solution here (The system is quickly becoming very content-coupled and almost symbiotic in nature, i.e the change of /ask path breaking the timer).

**Comment by timstableford** [comment]
We already do this, in say the name skill. We try and fetch the name.json and if it fails we create it with a default value.

I think we need this centralised database for skill configs exactly because of this interdependency between skills. If we don't create a way of accessing the data from other skills then it'll be done in a hacky way like it is now.

**Comment by patrickjquinn** [comment]
Okay lets go with it. I'll add the methods for saving skill info!

If it starts to become spaghetti code due to excessive interdependency we can look at compartmentalising the code and breaking everything up into clearly defined, black box modules

**Comment by timstableford** [comment]
Sounds like a good plan.

**Comment by timstableford** [comment]
By the way, I plan to make an SQL connector based on this interface as a secondary option. Maybe maintained in a separate repo if you don't think it fits in the core :)

**Comment by patrickjquinn** [comment]
Sounds good, I dont really see it as core if im honest so keeping it separate would suit me just find.

I've decided to basically maintain your auth structure and just move any 'save to fs' calls over to the db module. I want to re-stabilize the project (and fix the raspi client) and then we can look at building a roadmap that we can follow. I'm losing sight of any goals or milestones at this point haha

**Comment by timstableford** [comment]
I thought you might agree it's not quite core. Useful for shared instances though for sure.

What do you think needs stabilising in the core project? I might be able to help out with that :+1: 

A roadmap sounds like a great plan. As it stands I can see how to improve the architecture but not how to move towards your goal of it being smarter.

**Comment by patrickjquinn** [comment]
I'm currently torn as to how to proceed with diskdb solution. One options for the moment might be to stick with your JSON file solution. Scrap the db module for now and add it with a spec in the roadmap. I am hoping to get the multiuser support merged with the master so I can fix the raspi branch and we can host an instance remotely for both the iOS and Android clients to make use of. 

These changes are holding up project wide advancement (i.e there are more impactful, user/developer facing things we could be dealing with instead of this) so I think the local fs solution you've come up with will more than do for now (JSON being JSON, it can be dumped straight into a DB if the need arises in future)

What do you think?

**Comment by timstableford** [comment]
I'm okay with dropping the database idea for now. I have reservations about calling it multi-user though. There's 3 things that will definitely cause problems:
- Users setting the name of the assistant would be global.
- Users telling the assistant their name would be global.
- All events from timers are pushed to all users. There's not really an easy way to fix this one except tracking which user has connected from which socket.
In its current state you would have to disable timer for the multi-instance install I think.

**Comment by patrickjquinn** [comment]
Maybe just create an object for each user in each file (i.e name.json has a object in it for each user) which is essentially what we where doing with diskdb without the hassle of having to changed everything over. so the key would be the username.

As for socket, we would have to create a socket register which does exactly as you're proposing.

**Comment by syzer** [comment]
i would propose having `users` in the db and `sessions`,
this way each user could auth via fabeook/google/password/whatever
and we can expire users tokkens

**Comment by timstableford** [comment]
So in addition to what we're planning (auth with tokens and socket.io), we should support OAuth login?

**Comment by syzer** [comment]
its a standard nowdays.. not much biggie to implement

**Comment by syzer** [comment]
but if we go with ssl.. sockets should also be authenticated
i would recommend ussing XSS protections like that: 
https://www.npmjs.com/package/lusca

**Comment by syzer** [comment]
so plan would be add db.. maybe doker, add ssl...
restructure endpoints
add proper tests for intents

**Comment by timstableford** [comment]
We're already working on adding a DB with a generic interface. The project already has Docket support AFAIK. As to SSL, I've come across issues with this version of NodeJS/Express and dropped connections. For SSL on my copy I'm running an Apache proxy layer. There are already tests for intents that double as training data. On startup, all 'examples' in a skill are checked to make sure they're classified correctly. If it fails to classify on a skill with a hard rule then the server throws an error, if it fails on an intent based skill then it uses the example for retraining.

**Comment by syzer** [comment]
@timstableford wanna join effort?

**Comment by timstableford** [comment]
I already am, me and @patrickjquinn are working on the user_profiles and sqlite_db branch.

**Comment by syzer** [comment]
IMHO sql lite is not great for working with jsons

**Comment by timstableford** [comment]
We're not going to be using sqlite anyway. It's an intermediary for using a cloud database like AWS on a shared instance. The data is highly relational though so it did make sense. Propose your changes in a PR and @patrickjquinn will have a look.

**Comment by timstableford** [comment]
PR #38 created covering auth, and prep for SSL. Tested SSL using Apache proxy.

**Comment by timstableford** [comment]
@syzer You've suggested a lot of good ideas. Feel free to create PR's for any you feel are important and they'll almost certainly be merged in.
