### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by michelpa** [patrickjquinn/P-Brain.ai#29]
Hello,

I would like to know if i can help to support multilanguage (french for me) and how can i do.

Thanks.

**Comment by patrickjquinn** [comment]
Hi there, 

At the moment multi-language support isnt priority 1, but if you wanted to go about doing it, the simpliest solution would be to convert the input command (in a given language) into english and then convert the response back to the desire language.

Basically creating a language adapter would do the trick here.
