### ISSUE TITLE
sqlite_db version undefined

### ISSUE THREAD

**Issue by suhajdab** [patrickjquinn/P-Brain.ai#47]
**I get the following error on osx (node v7.7.1, Python 3.5.2)**

$ yarn & yarn start
[1] 31664
yarn install v0.21.3
yarn start v0.21.3
$ node server.js 
warning P-Brain.ai@0.5.3: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.66s.
Setting up database.
TypeError: Cannot read property 'version' of undefined
    at getVersion (/Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/sqlite_db/index.js:84:15)
...

Any ideas how to solve it?

**Comment by cemsterr** [comment]
Just to note; the same error occurs on Windows 10 as well. Dependencies are installed correctly.

**Comment by timstableford** [comment]
Thanks for reporting the bug. I've pushed up a fix. Let me know if it resolves it for you :)

**Comment by suhajdab** [comment]
**That worked, thanks!**

... but only until the next issue. :)
Should I open a new issue?

_Setting up database.
Setting default global values in database
Loading skills.
{ Error: Could not locate the bindings file. Tried:
 → /Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/node_modules/libxmljs/build/xmljs.node
 → /Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/node_modules/libxmljs/build/Debug/xmljs.node_

**Comment by cemsterr** [comment]
Thanks, @timstableford! 

**The fix helped me** get past the "version is undefined" issue, however it ended up with the following error:
Error: Cannot find module '/Users/cemsterr/Desktop/pbrainai/P-Brain.ai/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:470:15)
    (...)

I apparently had run "npm install" sometime, so I deleted the node_modules folder and got past the problem mentioned above.

Now there is an authentication related issue, but I'll figure that one out myself :)

**Comment by timstableford** [comment]
What's the authentication issue? Could be a bug or if not the docs certainly need updating.

**Comment by timstableford** [comment]
@cemsterr I've just run through, sanity checked initial login, and fixed a bug. Hopefully that's the one you meant.

**Comment by cemsterr** [comment]
Let me share the logs:

Setting up database.
Loading skills.
Training recognizer.
2 queries were not routed correctly, attempting re-education.
Re-education successful after 2 iterations.
Starting server.
Server started on http://localhost:4567
Warning! Promiscuous mode is enabled all logins will succeed.
Possibly deadly warning! Promiscuous admins is enabled. All new users will be admins and can view each others data.
Settings can be changed at http://localhost:4567/settings.html
_So far so good. Once I try and open localhost:4567 on Chrome, the following occurs:_

TypeError: Cannot read property 'token' of undefined
    at /Users/cemsterr/Desktop/pbrainai/P-Brain.ai/authentication/index.js:50:22
    at Generator.next (<anonymous>)
    (...)

**Comment by timstableford** [comment]
@suhajdab would you try deleting you node_modules folder and re-running yarn install? xml2js used to be a dependency but because of broken Windows compatibility we removed it a while back.

@cemsterr did you do a fresh pull? I just pushed up a fix for that issue. Thanks for sharing the logs for verification though! :)

**Comment by cemsterr** [comment]
@timstableford I hadn't done that. Now that I have, it seems to work like a charm! 
Thanks for the help, it was a nice start to my first open source contribution attempt :p

**Comment by suhajdab** [comment]
@timstableford Yep. That helped too!
Followed by:
```
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
  LIBTOOL-STATIC Release/xml.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/xml.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.7.1_1/bin/node" "/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/node_modules/libxmljs/build/Release"
gyp ERR! cwd /Users/suhajdab/Dropbox (onereason)/projects/_useful/P-Brain.ai/node_modules/libxmljs
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

**Comment by timstableford** [comment]
Apologies @suhajdab I don't think I can help with this one, I don't have a Mac. I know @patrickjquinn uses one. It could be that you're using a different node version to the recommended one. Or it could be this issue: https://github.com/libxmljs/libxmljs/issues/130

I would just generally recommend making sure you're using the versions recommended in the README.md

**Comment by suhajdab** [comment]
Alright. As the original issue has already been solved, I'll close this.
Thanks @timstableford

**Comment by patrickjquinn** [comment]
I'll check this out on my local device and report back as to wether or not I run into the same set of conditions. 👍
