### ISSUE TITLE
[Suggestion] Offline speech recognition

### ISSUE THREAD

**Issue by austinkregel** [patrickjquinn/P-Brain.ai#50]
Hey there, I just wanted to make sure you were aware of the offline speech recognition library [sonus](https://github.com/evancohen/sonus) which uses [Snowboy](https://snowboy.kitt.ai/) for offline key-word detection. 

I personally run ubuntu and had to do a bit of googling to make sure everything installed properly but overall it works rather well for what I use it for. :)

**Comment by TimSBSquare** [comment]
Sonus isn't actually offline speech recognition, just keyword detection. It works similarly to the Android app and Raspberry Pi client which use Snowboy and push the STT up to the cloud.
