### ISSUE TITLE
Update Hotword to Harry 

### ISSUE THREAD

**Issue by paramjit1992singh** [patrickjquinn/P-Brain.ai#51]
Hi Pat , I changed the hot word Brain to Harry in src/index.html file as you instructed in the comment section of your first video but nothing happened ,,Can you please help

**Comment by DevelopingUnicorn** [comment]
You can change the name from the Webinterface!

**Comment by DevelopingUnicorn** [comment]
Use "Set name to ..." or "Your name is ..."

**Comment by paramjit1992singh** [comment]
Thanks bro ,,,I was thinking to do it at the base level ,,,like for instance when you run the application for the first time how brain is coming , at that level i wanted to know how to update the name as i was trying to understand the code , thanks again for your help , and there is one more place i would want you to help me ,,,i have created some skill for this application like sending email , creating file and reading file and few others ,,,,but the list file skill that I made is not showing all the files in the folder thats created so can you look into it and suggest me the solution

**Comment by paramjit1992singh** [comment]
path to the my skills zip is https://github.com/paramjit1992singh/test
