### ISSUE TITLE
Current is work?

### ISSUE THREAD

**Issue by freenetwork** [patrickjquinn/P-Brain.ai#54]
Why i say hey Brain - nothing working? Mic enabled

**Comment by patrickjquinn** [comment]
I need more info. What browser are you currently using to access it with?

**Comment by freenetwork** [comment]
Chrome
OSX
mic Enabled
https://image.ibb.co/kpSSk6/2017_11_27_22_39_23.png

**Comment by patrickjquinn** [comment]
Thanks for reporting, I know Google have changed how the mic is accessed but i'm using it here without much issue. I'll dig into it now.

**Comment by freenetwork** [comment]
Thx. Good project. 
Do you think will added pocketsphinx js for activation pharase?

**Comment by patrickjquinn** [comment]
I just tested it there and it seems to be working fine, can you verify that you dont have an errors in the console? Also are Google cloud speech services available in your part of the world?

It could be added yes, I doubt i'll have time to do it though so if you want to add it simply submit a pull request :)

**Comment by freenetwork** [comment]
Thx. https://www.google.com/intl/en/chrome/demos/speech.html
Not work. problem in hardware or cloud. Thx
