### ISSUE TITLE
Help lol

### ISSUE THREAD

**Issue by DJJPISAWESOME** [patrickjquinn/P-Brain.ai#55]
Hi im looking to get into ai and coding and when I saw this I wanted in so I installed everything (on windows) and went to run it but when I did yarn start it just referenced me here: "https://yarnpkg.com/en/docs/cli/run" can you help?

**Comment by patrickjquinn** [comment]
Hi,

Have you tried using npm install and then non start, instead of yarn?

Kind Regards,

Patrick.

**Comment by DJJPISAWESOME** [comment]
Hi im very new to all this and im not sure by what you mean (I have installed node.js which has npm in it) im not sure i know what you mean by non start

**Comment by DJJPISAWESOME** [comment]
I figured it all out but why can't he fugue out simple math?

**Comment by patrickjquinn** [comment]
It’s can. How are you asking.

Kind Regards,

Patrick.

**Comment by DJJPISAWESOME** [comment]
Brain what's 2+2?

**Comment by patrickjquinn** [comment]
What are you getting back as a response?

**Comment by DJJPISAWESOME** [comment]
The current weather is 46
