### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by brunoshine** [patrickjquinn/P-Brain.ai#57]
Hi,

I removed all skills except the time and it started throwing the exception below. Any thoughts?
Thanks

λ yarn start
yarn run v1.5.1
warning package.json: License should be a valid SPDX license expression
$ node server.js
Using default SQLite database provider
Setting up database.
Setting default global values in database
Loading skills.
Training recognizer.
**TypeError: Cannot read property 'value' of undefined
    at classify (C:\temp\P-Brain.ai\api\core-ask.js:123:34)**
    at classify.next (<anonymous>)
    at onFulfilled (C:\temp\P-Brain.ai\node_modules\co\index.js:65:19)
    at C:\temp\P-Brain.ai\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at co (C:\temp\P-Brain.ai\node_modules\co\index.js:50:10)
    at toPromise (C:\temp\P-Brain.ai\node_modules\co\index.js:118:63)
    at next (C:\temp\P-Brain.ai\node_modules\co\index.js:99:29)
    at onFulfilled (C:\temp\P-Brain.ai\node_modules\co\index.js:69:7)
    at C:\temp\P-Brain.ai\node_modules\co\index.js:54:5
(node:31144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'value' of undefined
(node:31144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.22s.

**Comment by brunoshine** [comment]
I've built a simple module based on the hello skill and I get the same error as soon as I add examples:

function * hello_resp() {
    return {text: 'Hello World'}
}

const intent = () => ({
    keywords: ["hi"], module: 'hello'
})

const examples = () => (
    ['hi.', 'hello.']
)


module.exports = {
    get: hello_resp,
    intent,
    examples
}

**Comment by patrickjquinn** [comment]
I can’t remember if this version builds a static classifier.json which needs to be deleted when you change skills...there is probably something in the admin that needs to be reset. I’m away from my desk at the moment but tag Tim (the other contributor to this project) and ask him what the story is here. I’ll look at it when I’m home tonight.

Warm regards,

Patrick.

**Comment by brunoshine** [comment]
Thanks @patrickjquinn 

@timstableford any thoughts?
Thanks.

**Comment by timstableford** [comment]
That was certainly an interesting bug. I've reproduced the bug and resolved it in #58. Comment here if it's resolved for you or you have further issues.

**Comment by timstableford** [comment]
Closing from the lack of response, safe to assume this is resolved.
