### ISSUE TITLE
Make online with AWS

### ISSUE THREAD

**Issue by arnabadg17** [patrickjquinn/P-Brain.ai#59]
How can I upload and make online on hosting using amazon AWS.

**Comment by patrickjquinn** [comment]
Hey,

What exactly are you trying to do and what have you tried so far? I’ve hosted it on AWS without any issue.

Regards,

P.

**Comment by arnabadg17** [comment]
I uploaded it on ec2. the main problem is microphone not working in chrome! Help me.

Can you please send your hosting link?

**Comment by patrickjquinn** [comment]
You have to use https (generate a SSL cert using letsencrypt, look up using https with express instead of http) and the mic input will work in chrome.

I can’t share a link because it’s a private instance I’m using for another commercial project. Sorry.
