### ISSUE TITLE
Multiple Responses

### ISSUE THREAD

**Issue by Ashish117** [patrickjquinn/P-Brain.ai#62]
Multiple return is not possible so is there a way to get multiple responses 
For Example. Me: Download movie 
                       Brain: Download has started.
                       on download finish it should say. Brain: Download Completed

**Comment by patrickjquinn** [comment]
Hey! The platform is simple enough to modify and we can’t add use add specific features for everyone. I’d be more than happy to help you make the modifications yourself though!

**Comment by Ashish117** [comment]
I was just asking whether it’s possible or not

**Comment by timstableford** [comment]
Closing this as resolved since it can be done sending socket messages :)
