### ISSUE TITLE
Help with another voice

### ISSUE THREAD

**Issue by LavrenkovNV** [patrickjquinn/P-Brain.ai#63]
I try to add Russian, he recognizes everything well, but when I add a keyword in Russian to the weather module, he doesn’t see it and all the time says he doesn’t understand. You can not tell what needs to be corrected so that everything is recognized, maybe some kind of regular expression needs to be changed, or somewhere else corrected from en-UK to ru-RU

![2018-12-06 22-21-57](https://user-images.githubusercontent.com/44425646/49606849-83be3180-f9a5-11e8-8673-9d484bb24d90.png)

![2018-12-06 22-26-54](https://user-images.githubusercontent.com/44425646/49607081-0fd05900-f9a6-11e8-9383-9e40f7498ad1.png)

**Comment by patrickjquinn** [comment]
Interesting, Its possible the classification library in use here https://github.com/NaturalNode/natural doesn't support non-latin characters, let me check that and get back to you.

**Comment by patrickjquinn** [comment]
https://github.com/NaturalNode/natural/issues/463 this provides some insight into how you could change Natural's language engine.

**Comment by LavrenkovNV** [comment]
Please tell me where in your code you need to try to fix it?

> [NaturalNode/natural#463](https://github.com/NaturalNode/natural/issues/463) this provides some insight into how you could change Natural's language engine.


Please tell me where in your code you need to try to fix it?

**Comment by LavrenkovNV** [comment]
If I can, then I can develop 2 branches of the Russian-speaking community of this project. I do not know where to insert the code from the one you sent.

**Comment by patrickjquinn** [comment]
I believe it’s api/core.js ? Find where the Natural library is initialized and then you can change the language directly after 😊

Kind Regards,

Patrick Quinn.
