### ISSUE TITLE
New google

### ISSUE THREAD

**Issue by LavrenkovNV** [patrickjquinn/P-Brain.ai#65]
Help rewrite the fact / google module under Russian letters, it doesn't work, what's the problem?)
![2018-12-18 13-15-44](https://user-images.githubusercontent.com/44425646/50150651-4754d480-02c7-11e9-9022-3b68175e3ff0.png)

changed only index.js in the fact folder, did not change anything in the fact / google folder
Maybe need to change some kind of regular expression ???

**Comment by timstableford** [comment]
You'll need to provide some more details, a server log may be enough

**Comment by LavrenkovNV** [comment]
Could you help me and tell me how to enable or view server logs, collect and run the docker container like in your readme. my knowledge is lacking, I’ll be thankful to you
