### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by LavrenkovNV** [patrickjquinn/P-Brain.ai#67]
Hello, This is the text of my json processing module.The problem is: when I specify the port, it stops working and the **assistant says that he did not understand me.**
How to fix it???
my knowledge of the code is not strong, you maybe need to connect another one library.
but I do not understand how to connect them, I work through docker.
**help me please**

`constrequest = require('co-request')` 
` const util = require('util')` 
` const intent = () => ({` 
`     keywords: ['number qqq', 'number action qqq'],` 
`     module: 'abonent_oblgas'` 
` })` 
` function * abonent_oblgas_resp(query) {` 
` const request = require('request');` 
`     let country_res = request("http://192.168.10.55:8444/getabonentbynumberofcontract?number=10&id_podr=1")` 
`     country_res = JSON.parse(country_res.body)` 
`     const loc_string = country_res.city + ',' + country_res.country` 
 `    return loc_string.toLowerCase()` 
 `    return{text: 'works.'}` 
` }` 
` const examples = () => (` 
`     ['number 587', 'number action 144']` 
` )` 
` module.exports = {` 
 `    get: abonent_oblgas_resp,` 
  `   intent,` 
  `   examples` 
` }`

**Comment by timstableford** [comment]
Hi,

I suspect what's happening is that there's an error in your code that's causing a crash and you're getting the crash response. Check the server logs to see exactly what the error is.

From just looking through this quickly though there's a missing yield before your http request which is likely to cause a crash

**Comment by LavrenkovNV** [comment]
Could you help me and tell me how to enable or view server logs, collect and run the docker container like in your readme. my knowledge is lacking, I’ll be thankful to you

**Comment by LavrenkovNV** [comment]
> Hi,
> 
> I suspect what's happening is that there's an error in your code that's causing a crash and you're getting the crash response. Check the server logs to see exactly what the error is.
> 
> From just looking through this quickly though there's a missing yield before your http request which is likely to cause a crash

Could you help me and tell me how to enable or view server logs, collect and run the docker container like in your readme. my knowledge is lacking, I’ll be thankful to you
