### ISSUE TITLE
How enable server logs

### ISSUE THREAD

**Issue by LavrenkovNV** [patrickjquinn/P-Brain.ai#69]
Hello @timstableford @patrickjquinn Please help me to understand
Could you help me and tell me how to enable or view server logs, collect and run the docker container like in your readme. my knowledge is lacking, I’ll be thankful to you

**Comment by patrickjquinn** [comment]
Server logs aren't currently a feature beyond the standard Node.js console logs, you can add your own console.log output (or other print frameworks) to your custom skill and that will guide you in the right direction.
