### ISSUE TITLE
ELECTRON INTEGRATION - AUTHENTICATION ISSUE

### ISSUE THREAD

**Issue by andresdev16** [patrickjquinn/P-Brain.ai#76]
Hello, I am integrating and because to log in it is necessary to do it from a pop-up window, in electron it is not possible to do it. I would like to know what is the fraction of code that is responsible for displaying this pop-up window and how I could do to login with HTML.

I'm getting the message "unauthorized".

**Comment by patrickjquinn** [comment]
Electron isnt supported as it doesn’t allow for the good speech API,

Does it work for you in the browser?

**Comment by andresdev16** [comment]
What alternative for electron? . In the browser it is perfect, anyway I would like to change from a popup window to HTML.

**Comment by timstableford** [comment]
It uses HTTP basic auth. Closing as a duplicate of #77 where I've gone into some detail.
