### ISSUE TITLE
MySQL does not work

### ISSUE THREAD

**Issue by andresdev16** [patrickjquinn/P-Brain.ai#78]
I have mysql provider, and the index.js in /db/mysql/ dont insert or get the data in my mysql database. How can i enable mysql?

**Comment by timstableford** [comment]
It defaults to Sqlite3. So I think you need to have a config.json in the root folder and set databaseType to mysql and then also put a databaseArguments object in there with host, username, password and database. See https://github.com/patrickjquinn/P-Brain.ai/blob/master/db/index.js

**Comment by andresdev16** [comment]
Oh, thank you very much, It's work.

**Comment by andresdev16** [comment]
Expected "payload" to be a plain object. When i try sign in
