### ISSUE TITLE
Continuous Chat

### ISSUE THREAD

**Issue by tb100** [patrickjquinn/P-Brain.ai#79]
I've got a question about using skills. I'm trying to write a food/restaurant skill using the EatStreet API. How do I add a continuous chat? Example:

**You: Find a restaurant.
Bot: Okay, where are you?
You: "location".
Bot: Great! Here are some restaurants near you! ...**

Right now, once the bot has returned text, it's not listening to something else said by the user. Is there a way I can get this to work? Thanks!

**Comment by timstableford** [comment]
Take a look at the personality skill here, it shows how to access the conversation history https://github.com/patrickjquinn/P-Brain.ai/blob/master/skills/personality/index.js#L163

**Comment by tb100** [comment]
Okay! So it looks like I can use the `getConversation(user, device)` function to see how long this skill has been active, check the last response, and then go from there. I'm guessing if I want to have more than one, it would get me the last response, and I could keep doing it over and over. Thanks so much for your help @timstableford!

**Comment by patrickjquinn** [comment]
You can always open the listening session in the callback of the response, maybe have a new object that gets returned in the response object and have a handler for it in the client. Ie a bool that allows for conditional “allowsFollowUp” checks to be made.

But yes, a bit of work to do to get it working the way you want but not a massive amount.
