### ISSUE TITLE
Voice is not heard

### ISSUE THREAD

**Issue by robert478** [patrickjquinn/P-Brain.ai#83]
Hello to anyone that is listening. I have installed  P-Brain.ai with no issues on Kubuntu linux and when i speak nothing happens, it say's that the web browser is using my mic but nothing happens. i've tried also in firefox etc. I've also tested my mic with arecord  so it works. What should i do  or is this a glitch with Kubuntu 18.4.
Best Regards and hope to hear from someone. 
also can email me at uboat478@gmail

Respectfully Bogs

**Comment by patrickjquinn** [comment]
Specifically what browser are you using? It requires Chrome and not chromium or electron or Firefox.

**Comment by robert478** [comment]
Good eve Patrick, i'm using Chrome but i tried all of them and still the same

**Comment by patrickjquinn** [comment]
Hmmm when you open the chrome inspector, are there any errors in the console? I’ve not tested the project in a while so I’m not sure what’s changed. Do you have another machine running a different OS that you can test it on? Ie if you have chrome on your phone you should be able to access it on your Android phone via the kubuntus ip address rather than local host

**Comment by robert478** [comment]
excuse me i'm stupid, what is chrome inspector

**Comment by robert478** [comment]
no this is a laptop running Kubuntu 18.4

**Comment by robert478** [comment]
ok i'm trying to learn this and to you i must be a 3 yr old. but i've open chrome inspect what should I look for
it shows no errors

**Comment by patrickjquinn** [comment]
Not at all, you managed to figure it out in the time between me replying and checking my phone so good on you. I’ll tell you what, I’ll fire up P-Brain on my Linux machine to see what going on here. If Tim is about tomorrow he might also be able to check on his machine. If I don’t respond by tomorrow evening follow up with a reminder here 🙂

**Comment by robert478** [comment]
and if i try on my cell phone http://localhost:4567 its just a blank page

**Comment by robert478** [comment]
Thank you so much, i'm trying to do this because my eye site is failing and it helps me at the ripe ole age of 75. You guys are wonderful in helping

**Comment by patrickjquinn** [comment]
To do this on your phone you’d need to get the IP address of your Linux machine and replace local host with that (localhost is the current machine you’re running on and given p-brain isn’t running on your phone it won’t be available)

It’s quite late here but I’ll send you on a guide  to get this address tomorrow.

And don’t worry, let me know what tasks you’re looking to voice controls and I’ll help get that set up for you. I did a custom build of p-brain for my father so he could come down into the kitchen, say good morning to the Pc and it would automate his morning routine (local news radio starts, his favourite website opens and the local obituary site too...he’s oddly fascinated by obituaries)

Here to help

**Comment by robert478** [comment]
Good on you, your a good son.  Bless you

**Comment by robert478** [comment]
also this is rick from next door who  has been trying to help him , i know  you will see this tomorrow , but he has this when we log in.

yarn run v1.22.4
warning package.json: License should be a valid SPDX license expression
$ node server.js
Using default SQLite database provider
Could not load SQLite3 Config
Setting up database.
SQLite DB: pbrain.db
Loading skills.
Training recognizer.
3 queries were not routed correctly, attempting re-education.
Expected (fact), used (weather) for: 'What's 2+2?'
Expected (rick), used (fact) for: 'Never gonna give you up.'
Expected (trip), used (fact) for: 'Let's go to Mordor.'
Re-education successful after 4 iterations.
Starting server.
Server started on http://localhost:4567
Warning! Promiscuous mode is enabled all logins will succeed.
Possibly deadly warning! Promiscuous admins is enabled. All new users will be admins and can view each others data.
Settings can be changed at http://localhost:4567/settings.html
we hope this helps
rick and bogs

**Comment by robert478** [comment]
Good afternoon Pat,
Could you find out the problem or is it something we did during installation?
Bst Regards
Bogs

**Comment by robert478** [comment]
Thank you for your time an effort. Have a great evening

**Comment by patrickjquinn** [comment]
Hey Robert, havent managed to duplicate the issue on my end yet, can you tell me the process of getting the server up and running and wether or not the mic is enabled inside the chrome window (immediate left of the url bar).

**Comment by robert478** [comment]
Good Afternoon Pat,
I have Kubuntu 20.04 and yes i use google chrome. it shows that little red
dot saying fo the microphone on chrome. and down on the tool bar it shows
the mic being used by the browser but it doesnt reply or open anything, the
browser screen is blank other than the blue microphone and  the msg next to
it.
I hope this helps
Best regards
Bogs

**Comment by patrickjquinn** [comment]
Oki doke, pushed a new commit that should solve this, say the word "Brain", wait for him to say yes and then proceed with your command. If he's not speaking back to you, click the mic icon first and then try.

**Comment by patrickjquinn** [comment]
(first do a pull before trying the above ;) )

**Comment by robert478** [comment]
Forgive me Pat, but im not sure as to what you mean by a pull first. I
wished I had your BRAINS for this.
Best Regards
Bogs

**Comment by robert478** [comment]
when I try to start now i get this error code ~/P-Brain.ai$ yarn start
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

nothing is working now,

**Comment by robert478** [comment]
ok this time i tried just yarn and got this code:
yarn
yarn install v1.22.4
warning package.json: License should be a valid SPDX license expression
warning P-Brain.ai@0.6.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this
module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility
check. Excludi
ng it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility
check. Excludin
g it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 109.19s.

Im not sure if something isnt loading correctly or not.
Bogs

**Comment by robert478** [comment]
GREAT IT WORKS NOW , THE LADY CAN HEAR ME. I'm not sure as to how to make
her open youtube etc. she say's she doesnt understand. Do I have to set
anything up? Thank you so much.
Bogs
